/* Splits data/content.js (the file you edit — all 12 languages together) into the files the
   website actually loads, so a visitor only downloads their own language:
     data/content-core.js    = everything that is not language text (LANGS, UI, HEROES, guide list,
                               hero-card ratings, journey data …) + the loader
     data/content-<lang>.js  = that language's guide sections, glossary, hero-card text, journey
                               translations — plus the English copy as fallback
   Run by .github/workflows/split-content.yml on every change to data/content.js.
   Nothing here is edited by hand: change data/content.js and this script regenerates the rest. */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const src = fs.readFileSync(path.join(ROOT, "data/content.js"), "utf8");

// run content.js exactly as the browser would, then read the globals it defined
const D = {};
new Function("D", src + `
  D.LANGS = LANGS; D.UI = UI; D.HEROES = HEROES; D.GLOSSARY = GLOSSARY; D.GUIDES = GUIDES;
  D.JOURNEY = typeof JOURNEY !== "undefined" ? JOURNEY : [];
  D.JOURNEY_TR = typeof JOURNEY_TR !== "undefined" ? JOURNEY_TR : {};
  D.JOURNEY_UI = typeof JOURNEY_UI !== "undefined" ? JOURNEY_UI : {};
  D.HERO_CARDS = typeof HERO_CARDS !== "undefined" ? HERO_CARDS : [];
  D.HERO_CARD_UI = typeof HERO_CARD_UI !== "undefined" ? HERO_CARD_UI : {};
`)(D);

const codes = D.LANGS.map((l) => l.code);
const J = (o) => JSON.stringify(o);

/* ---- core: language-neutral data ---- */
const coreGuides = {};
for (const [id, g] of Object.entries(D.GUIDES)) {
  const { sections, ...rest } = g;
  coreGuides[id] = { ...rest, sections: {} };          // sections are filled in by content-<lang>.js
}
const coreCards = D.HERO_CARDS.map((h) => { const { t, ...rest } = h; return { ...rest, t: {} }; });

const core = `/* GENERATED by scripts/split-content.js from data/content.js — do not edit by hand. */
const CONTENT_VERSION = "${hash(src)}";
const LANGS = ${J(D.LANGS)};
const UI = ${J(D.UI)};
const HEROES = ${J(D.HEROES)};
const GLOSSARY = {};
const GUIDES = ${J(coreGuides)};
const JOURNEY = ${J(D.JOURNEY)};
const JOURNEY_TR = {};
const JOURNEY_UI = ${J(D.JOURNEY_UI)};
const HERO_CARD_UI = {};
const HERO_CARDS = ${J(coreCards)};
/* Language files call this to merge their text into the objects above. */
const CONTENT_LOADED = {};
function contentMerge(lang, c) {
  for (const id in c.glossary) { if (!GLOSSARY[id]) GLOSSARY[id] = {}; Object.assign(GLOSSARY[id], c.glossary[id]); }
  for (const id in c.sections) if (GUIDES[id]) Object.assign(GUIDES[id].sections, c.sections[id]);
  for (const l in c.journeyTr) JOURNEY_TR[l] = c.journeyTr[l];
  for (const k in c.heroCardUi) { if (!HERO_CARD_UI[k]) HERO_CARD_UI[k] = {}; Object.assign(HERO_CARD_UI[k], c.heroCardUi[k]); }
  for (const id in c.heroCards) { const h = HERO_CARDS.find((x) => x.id === id); if (h) Object.assign(h.t, c.heroCards[id]); }
  CONTENT_LOADED[lang] = true;
}
/* Loads data/content-<lang>.js once; resolves when its text is merged. */
function loadContentLang(lang) {
  if (CONTENT_LOADED[lang]) return Promise.resolve();
  loadContentLang.pending = loadContentLang.pending || {};
  if (!loadContentLang.pending[lang]) loadContentLang.pending[lang] = new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = "data/content-" + lang + ".js?v=" + CONTENT_VERSION;
    s.onload = () => resolve(); s.onerror = () => { delete loadContentLang.pending[lang]; reject(new Error("content-" + lang)); };
    document.head.appendChild(s);
  });
  return loadContentLang.pending[lang];
}
`;

/* ---- one file per language: its own text + English fallback ---- */
function pickLangs(map, langs) {
  const out = {};
  for (const l of langs) if (map && map[l] !== undefined) out[l] = map[l];
  return out;
}
function langFile(lang) {
  const langs = lang === "en" ? ["en"] : [lang, "en"];
  const glossary = {};
  for (const [id, m] of Object.entries(D.GLOSSARY)) glossary[id] = pickLangs(m, langs);
  const sections = {};
  for (const [id, g] of Object.entries(D.GUIDES)) sections[id] = pickLangs(g.sections, langs);
  const heroCardUi = {};
  for (const [k, v] of Object.entries(D.HERO_CARD_UI)) {
    // roles is a map of role -> {lang: text}; the rest are {lang: text}
    heroCardUi[k] = k === "roles" ? Object.fromEntries(Object.entries(v).map(([r, m]) => [r, pickLangs(m, langs)])) : pickLangs(v, langs);
  }
  const heroCards = {};
  for (const h of D.HERO_CARDS) heroCards[h.id] = pickLangs(h.t, langs);
  const journeyTr = pickLangs(D.JOURNEY_TR, langs);
  return `/* GENERATED by scripts/split-content.js from data/content.js — do not edit by hand. */
contentMerge(${J(lang)}, ${J({ glossary, sections, journeyTr, heroCardUi, heroCards })});
`;
}

function hash(s) {
  return require("crypto").createHash("sha1").update(s).digest("hex").slice(0, 10);
}

fs.writeFileSync(path.join(ROOT, "data/content-core.js"), core);
console.log(`content-core.js: ${Buffer.byteLength(core)} bytes`);
for (const code of codes) {
  const text = langFile(code);
  fs.writeFileSync(path.join(ROOT, `data/content-${code}.js`), text);
  console.log(`content-${code}.js: ${Buffer.byteLength(text)} bytes`);
}
